"""Add estimate model

Revision ID: 535123a2bf33
Revises: a93db12b29bf
Create Date: 2026-07-29 14:59:07.943776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535123a2bf33'
down_revision = 'a93db12b29bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parts_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate')
    # ### end Alembic commands ###
