"""Create admin table

Revision ID: 837328a4a997
Revises: 8294c041c136
Create Date: 2026-07-23 16:14:01.998355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837328a4a997'
down_revision = '8294c041c136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
