"""Add internal notes to service requests

Revision ID: a93db12b29bf
Revises: 521ef83c8898
Create Date: 2026-07-23 18:19:34.502706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93db12b29bf'
down_revision = '521ef83c8898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('internal_notes')

    # ### end Alembic commands ###
